name: Main

on:
  push:
    # tags:
    #   - "v*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ./zip.sh
      - run: ls -al
    #   - name: Release
    #     uses: softprops/action-gh-release@v1
    #     with:
    #       files: |
    #         perf-limit-xiaomi-12-*.zip
